force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countrys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ISO_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Country_Code__c</fullName>
    <label>ISO Country Code</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountService.cls
public with sharing class AccountService {
    public static final Map<String, Id> MAP_ISO_COUNTRY {
        get { 
            if (MAP_ISO_COUNTRY==null) {
                Map<String, Id> mutableMapISOCountry = new Map<String, Id>();
                for (Country__c oneCountry : [SELECT id, ISO_Country_Code__c FROM Country__c]) {
                    mutableMapISOCountry.put(oneCountry.ISO_Country_Code__c, oneCountry.Id);
                }
                return mutableMapISOCountry;
            } 
            return MAP_ISO_COUNTRY;
            
        }
        private set;
    }
}