force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countrys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region, where country located</description>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Countrys</relationshipLabel>
    <relationshipName>Countrys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Employees that works in company</description>
    <label>Employee</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>65</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Sales_Team__c.field-meta.xml
<CustomField>
    <fullName>Sales_Team__c</fullName>
    <label>Sales Team</label>
    <referenceTo>Sales_Team__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Sales_Team__c.field-meta.xml
<CustomField>
    <fullName>Sales_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Team</label>
    <referenceTo>Sales_Team__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Team__c/Sales_Team__c.object-meta.xml
<CustomObject>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Team__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Employee__c.Sales_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Sales Teams</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountOwnerChangerTest.cls
@isTest
private class AccountOwnerChangerTest {
    @TestSetup
    static void makeData(){
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[] {
                Region__c.SObjectType,
                Country__c.SObjectType,
                Account.SObjectType
            }
        );
        Sales_Team__c saleTM = new Sales_Team__c(Name='TestTeam');
        insert saleTM;
        Employee__c empl= new Employee__c(Name='Jon',
                                        Last_Name__c='Adams',
                                        Sales_Team__c=saleTM.Id);
        insert empl;
        saleTM.Lead__c=empl.id;
        update saleTM;
        Region__c region = new Region__c(Name='Africa');
        uow.registerNew(region, Region__c.Sales_Team__c, saleTM);
        Country__c country = new Country__c(Name='Nigeria');
        uow.registerNew(country, Country__c.Region__c, region);
        Account acc = new Account(Name='Testing');
        uow.registerNew(acc, Account.Country__c, country);
        uow.commitWork();
    }
    @isTest
    static void onLeadOwnersTest() {
        AccountOwnerChanger accOwnChng = new AccountOwnerChanger();
        Employee__c employee = [SELECT id FROM Employee__c WHERE Name='Jon' LIMIT 1];
        accOwnChng.onLeadOwners();
        Account acc = [SELECT id, Owner__c FROM Account WHERE Country__r.Name='Nigeria' LIMIT 1];
        System.assertEquals(employee.id, acc.Owner__c);
    }
    
    @isTest
    static void ChangeAccOwnerTest() {
        Test.startTest();
        String CRON_EXP = '0 0 * * * ?';
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP,
            new ChangeAccOwner());
        Account acc = [SELECT id, Owner__c FROM Account WHERE Country__r.Name='Nigeria' LIMIT 1];
        System.assertEquals(null, acc.Owner__c);
        Test.stopTest();
        acc = [SELECT id, Owner__c FROM Account WHERE Country__r.Name='Nigeria' LIMIT 1];
        Employee__c employee = [SELECT id FROM Employee__c WHERE Name='Jon' LIMIT 1];
        System.assertEquals(employee.id, acc.Owner__c);
    }
}